### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by khan-c** [khan-c/PlayThis#5]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by khan-c** [comment]
Search feature implemented.
+ can play searched songs out of search page
+ can play playlists out of search page
+ can click to playlist show page out of search page
+ can click to user page out of search page
may look to implement artist and album pages and the corresponding search results in the future...

**Comment by AAlfarho** [comment]
Great job, the overall search functionality looks and works great.
The fact that we can play the playlist or song directly is amazing, kudos for that feature
A couple of details.
+ When trying to add a song to a playlist, the text _Add to playlist_ and _Top results_ overlap.
+ I found an issue trying to play a particular song. Steps to reproduce:
  + Search query was `a`
  + Start reproducing playlist `Dreamy`.
  + Hit the _next_ button.
  + Try to reproduce a single song, in this case `garden`.
  + The song will not play and theres a missing image icon in the media player, looks like the song state was not loaded?

**Comment by khan-c** [comment]
Those bugs should be fixed now. The second bug seemed to be an issue with how I implemented playback and going through songs and next songs. Might look to refactor in the future.

**Comment by AAlfarho** [comment]
Great job, with those 2 bugs fixed, MVP is completed, kudos!
