### ISSUE TITLE
PA Review: Continuous play while navigating

### ISSUE THREAD

**Issue by khan-c** [khan-c/PlayThis#6]
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by khan-c** [comment]
Implemented Features
+ Continuous play
+ Moving to next song on song end and when next button is clicked
+ Previous button
  + Moving to start of song if song has been playing for > 2 seconds
  + Moving to previous song
+ Stop play when end of playlist is reached
+ Play music when play button on playlist image is clicked
+ Play music when play button on playlist show page is clicked
+ Play individual song when individual song play button is clicked
+ Play individual song when song list item is double clicked
+ Volume slider
  + Volume mute when clicking volume icon
+ Play progress bar
  + Changes song position on click and slide

**Comment by AAlfarho** [comment]
Great Job on the continuous playing media, great selection too.
A couple of details.

+ I noticed that on the show playlist component (`/#/playlist/13`), if you hit play, the playlist will start without errors, however, if we click directly into any songs of such playlist the media player stops and disappears.
+ The _current song_ display on the media player components shows an artist name underlined, which naturally would mean we can click on the artist, until such future feature is enabled I would suggest removing the underline from underneath the artist's name, what do you think?

**Comment by khan-c** [comment]
These bugs should be fixed now. :)

**Comment by AAlfarho** [comment]
God job debugging that tricky issue.
MVP completed.
