### ISSUE TITLE
PA Review: Following playlists / Friending users

### ISSUE THREAD

**Issue by khan-c** [khan-c/PlayThis#7]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by khan-c** [comment]
The browse display should look better now. User playlists have a default image from the first song in the playlist. I tried to do something to what Spotify did where they take the first four songs and their album images and make a 2x2 grid of those photos... I got it to work, but it made everything lag too much, so I took it away and just used the single image.

**Comment by AAlfarho** [comment]
Great job with the new layout.
The new seeds bring a new look and feel to the app that showcases all of your work.
Last coding MVP completed, kudos !!
